spring:
  application:
    name: atg-booking
  flyway:
    enabled: true
    clean-on-validation-error: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;;DB_CLOSE_DELAY=-1;Mode=Oracle
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: ''
server:
  port: 8081
